#
#    ,---.                                  ,--.
#   /  O  \,--.  ,--.,---.  ,---. ,--,--. ,-|  | ,---.
#  |  .-.  |\  `'  /| .-. || .--'' ,-.  |' .-. || .-. |
#  |  | |  | \    / ' '-' '\ `--.\ '-'  |\ `-' |' '-' '
#  `--' `--'  `--'   `---'  `---' `--`--' `---'  `---'


# Almost all the things in the website can be customized from here.
# Changing title and description according to your website requirement is important.

# Footer stuff here....TODO (sskakles) get this to replicate elsewhere
title: Melissa "Missy" Bell 
title-min: Missy Bell
title-creds: OTR, DRS, CDI, CPT
#title.creds: "OTR, DRS, CDI, CPT"
description: Safe Driving and Rehabilitation
email: missybell.atx@gmail.com # The contact form submission will be done to this email address.
phone: (512) 689-0236
url: https://www.safedrivingrehab.com
default-image: /images/steering-wheel.png #/images/avocado-cover.png # This image will be shown on sharing any page on social media. For example: Homepage, about page etc. This image should be bigger than 200x200px. This image is not used for posts. Posts use their own image mentioned in individual posts.

# Author details shows up at the end of every article/blog
author:
    name: Melissa "Missy" Bell
    bio: "Missy is a licensed Occupational Therapist and Driving Rehabilitation Specialist with pediatric and driving rehabilitation experience since 2001. She owned and operated a Driving Readiness Program for Teens as a part of her specialty OT/Educational Support Services clinic, Extra Credit! LLC. <br/><br/>Missy is advancing her skills through mentorship and advanced education to work with additional populations and for certification in the field. She has obtained AOTA driving badges in adolescent driving, and adult driving and community mobility levels I, II, III and is a CarFit OT technician. Missy is an ADED member and part of a task force working to improve a national safe driving standards for teens with special needs."
    image: author-image.jpg # Choose a 200x200px image and place it inside /images directory.
    #facebook: https://www.facebook.com/missybell.atx
    #twitter: https://twitter.com
    #quora: https://www.quora.com/
    linkedin: https://www.linkedin.com/in/melissabellatx/

# Kramdown is supported by Github
markdown: kramdown

# Mathjax setting
enable-mathjax: yes

# Charts
enable-chartjs: yes
  
# This defines how the URLs should look like
permalink: /blog/:title/

# Pagination - Posts per page in the blog index
paginate: 4
paginate_path: /blog/page:num/

# Define titles for the sections
name: Melissa "Missy" Bell
projects: All things OTR, DRS, CDI, and CPT


# Jekyll will read contents inside _pages only if we tell it to
include:
    - _pages

# Google Ananlytics Tracker
#analytics: UA-92266803-2  # Sign up with Google analytics and replce with your analytics ID

#Tawk.to integration
#tawkto-id: 5cb170e9c1fe2560f3fea30c # Sign up with tawk.to and go to Admin >> Property settings and replace the Site ID here
#tawkto-id: 5cdf2b222846b90c57af1bed # This is our new tawk.to id (sskakles)

# Share buttons
#share: yes # Change it to `no` to remove share buttons.


# Comments by Disqus # Sign up with Disqus to get your shortcode. Leave it blank if you do not want to run diqus code on the website. # webjeda-demo
# disqus: missybell-atx


#
#   ,-----.                                                    ,--.
#  '  .--./ ,---. ,--,--,--. ,---. ,--.--. ,---.  ,---.  ,---. `--' ,---. ,--,--,
#  |  |    | .-. ||        || .-. ||  .--'| .-. :(  .-' (  .-' ,--.| .-. ||      \
#  '  '--'\' '-' '|  |  |  || '-' '|  |   \   --..-'  `).-'  `)|  |' '-' '|  ||  |
#   `-----' `---' `--`--`--'|  |-' `--'    `----'`----' `----' `--' `---' `--''--'
#                           `--'
# All compression variables are declared here.

sass:
 style: compressed

#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

####################################################################################################

destination: _avocado

exclude:
    - .git
    - .jekyll-cache

# These plugins are supported by github by default and can be installed locally using ruby gems
plugins:
    - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
    - jekyll-feed       # Adds feed to the website at /feed.xml
    - jekyll-paginate   # Used for sorting posts by page numbers.
    - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
