- title:      Professional Assement
  description:  Providing comprehensive medical assessment and reports for driving needs across the age span for, Driving Readiness Screening for Adolescents, Potential to Drive OT Clinical Evaluations for Adults, and Behind the Wheel Driving Rehab Specialist Assessment. Individual Driving Plans (IDP) with recommendations based on supporting evidence can be utilized to get further training and support services.
  fa-icon:      fa-object-group
  link:         

- title:      Mobile Services
  description:  Serving the Austin-Metro Region and beyond for convenience and necessity.  Most clients prefer assessment, training, and consultation in a comfortable and familiar setting whenever possible. If services are requested through a clinic, hospital, or driving school those options can be discussed as a part of the individualized driving plan. Due to payer restrictions and for liability reasons, some service limitations may be identified.		
  fa-icon:      fa-code
  link:         

- title:      Support and Education
  description:  Determining if driving or other community mobility options is the best and safest choice for yourself or a family member can be a difficult experience. Clear, regular communication as well as therapeutic support is a necessary component to assisting with these difficult decision making processes. In cases where adaptive driving equipment or family-assisted driver training may be beneficial, guidance can be offered.		
  fa-icon:      fa-paper-plane-o
  link:
